// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: internal/proto/session.proto

package sessionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	mi := &file_internal_proto_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_session_proto_rawDescGZIP(), []int{0}
}

func (x *SessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SessionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Claims        map[string]string      `protobuf:"bytes,2,rep,name=claims,proto3" json:"claims,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Expiry        int64                  `protobuf:"varint,3,opt,name=expiry,proto3" json:"expiry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_internal_proto_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_session_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreateSessionRequest) GetClaims() map[string]string {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *CreateSessionRequest) GetExpiry() int64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

type SessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Claims        map[string]string      `protobuf:"bytes,3,rep,name=claims,proto3" json:"claims,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_internal_proto_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_session_proto_rawDescGZIP(), []int{2}
}

func (x *SessionResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *SessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionResponse) GetClaims() map[string]string {
	if x != nil {
		return x.Claims
	}
	return nil
}

var File_internal_proto_session_proto protoreflect.FileDescriptor

const file_internal_proto_session_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/proto/session.proto\x12\tsessionpb\"\xce\x01\n" +
	"\x0eSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12C\n" +
	"\bmetadata\x18\x03 \x03(\v2'.sessionpb.SessionRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcb\x01\n" +
	"\x14CreateSessionRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12C\n" +
	"\x06claims\x18\x02 \x03(\v2+.sessionpb.CreateSessionRequest.ClaimsEntryR\x06claims\x12\x16\n" +
	"\x06expiry\x18\x03 \x01(\x03R\x06expiry\x1a9\n" +
	"\vClaimsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc1\x01\n" +
	"\x0fSessionResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12>\n" +
	"\x06claims\x18\x03 \x03(\v2&.sessionpb.SessionResponse.ClaimsEntryR\x06claims\x1a9\n" +
	"\vClaimsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xa8\x01\n" +
	"\x0eSessionService\x12H\n" +
	"\x0fValidateSession\x12\x19.sessionpb.SessionRequest\x1a\x1a.sessionpb.SessionResponse\x12L\n" +
	"\rCreateSession\x12\x1f.sessionpb.CreateSessionRequest\x1a\x1a.sessionpb.SessionResponseB.Z,github.com/harry-urek/urek/v/proto/sessionpbb\x06proto3"

var (
	file_internal_proto_session_proto_rawDescOnce sync.Once
	file_internal_proto_session_proto_rawDescData []byte
)

func file_internal_proto_session_proto_rawDescGZIP() []byte {
	file_internal_proto_session_proto_rawDescOnce.Do(func() {
		file_internal_proto_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_session_proto_rawDesc), len(file_internal_proto_session_proto_rawDesc)))
	})
	return file_internal_proto_session_proto_rawDescData
}

var file_internal_proto_session_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_proto_session_proto_goTypes = []any{
	(*SessionRequest)(nil),       // 0: sessionpb.SessionRequest
	(*CreateSessionRequest)(nil), // 1: sessionpb.CreateSessionRequest
	(*SessionResponse)(nil),      // 2: sessionpb.SessionResponse
	nil,                          // 3: sessionpb.SessionRequest.MetadataEntry
	nil,                          // 4: sessionpb.CreateSessionRequest.ClaimsEntry
	nil,                          // 5: sessionpb.SessionResponse.ClaimsEntry
}
var file_internal_proto_session_proto_depIdxs = []int32{
	3, // 0: sessionpb.SessionRequest.metadata:type_name -> sessionpb.SessionRequest.MetadataEntry
	4, // 1: sessionpb.CreateSessionRequest.claims:type_name -> sessionpb.CreateSessionRequest.ClaimsEntry
	5, // 2: sessionpb.SessionResponse.claims:type_name -> sessionpb.SessionResponse.ClaimsEntry
	0, // 3: sessionpb.SessionService.ValidateSession:input_type -> sessionpb.SessionRequest
	1, // 4: sessionpb.SessionService.CreateSession:input_type -> sessionpb.CreateSessionRequest
	2, // 5: sessionpb.SessionService.ValidateSession:output_type -> sessionpb.SessionResponse
	2, // 6: sessionpb.SessionService.CreateSession:output_type -> sessionpb.SessionResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_proto_session_proto_init() }
func file_internal_proto_session_proto_init() {
	if File_internal_proto_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_session_proto_rawDesc), len(file_internal_proto_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_session_proto_goTypes,
		DependencyIndexes: file_internal_proto_session_proto_depIdxs,
		MessageInfos:      file_internal_proto_session_proto_msgTypes,
	}.Build()
	File_internal_proto_session_proto = out.File
	file_internal_proto_session_proto_goTypes = nil
	file_internal_proto_session_proto_depIdxs = nil
}
